[server]
#runOnSave = true # Enable hot-reloading of the app when files are saved (when in development mode)

[client]
toolbarMode = "viewer" # Set the toolbar mode to 'viewer' for a cleaner interface
